##
# pygame_maze.py
# Wed 06 Oct 2021
# Takes a generated maze and puts it in pygame
# S
import pygame
from sys import argv

from hunt_and_kill import DIRS, O_DIRS
import hunt_and_kill

CELL_SIZE = 7

def draw_maze(screen, maze, width, height, fg):
    """
    Draws the maze! What did you expect?
    """
    # Line thickness
    STROKE = CELL_SIZE // 5

    # This function is just so useful
    maze_idx = lambda p: p[1] * width + p[0]

    # First of all, draw borders.
    f_width = width * CELL_SIZE
    f_height = height * CELL_SIZE

    pygame.draw.line(screen, fg, (0, 0), (f_width, 0), STROKE)
    pygame.draw.line(screen, fg, (f_width, 0), (f_width, f_height), STROKE)
    pygame.draw.line(screen, fg, (f_width, f_height), (0, f_height), STROKE)
    pygame.draw.line(screen, fg, (0, f_height), (0, 0), STROKE)

    del f_width, f_height

    # Start drawin the stuff
    for y in range(height):
        for x in range(width):
            point = maze[maze_idx((x, y))]

            # -- NORTH
            if not (point & DIRS["N"]):
                pygame.draw.line(screen, fg,
                        (x * CELL_SIZE, y * CELL_SIZE), 
                        ((x + 1) * CELL_SIZE, y * CELL_SIZE),
                        STROKE)

            # -- EAST
            if not (point & DIRS["E"]):
                pygame.draw.line(screen, fg,
                        ((x + 1) * CELL_SIZE, y * CELL_SIZE), 
                        ((x + 1) * CELL_SIZE, (y + 1) * CELL_SIZE),
                        STROKE)

            # -- SOUTH
            if not (point & DIRS["S"]):
                pygame.draw.line(screen, fg,
                        (x * CELL_SIZE, y * CELL_SIZE + CELL_SIZE), 
                        ((x + 1) * CELL_SIZE, (y + 1 ) * CELL_SIZE),
                        STROKE)

            # -- WEST
            if not (point & DIRS["W"]):
                pygame.draw.line(screen, fg,
                        (x * CELL_SIZE, y * CELL_SIZE), 
                        (x * CELL_SIZE, (y + 1) * CELL_SIZE),
                        STROKE)



def main(width = 10, height = 10, *args):
    """
    Display a maze generated by the hunt and kill algorithm
    """
    BG = pygame.Color(0xF0F4EEFF)
    FG = pygame.Color(0x3C3C4CFF)

    pygame.init()
    clock = pygame.time.Clock()

    # TODO: Add padding
    screen = pygame.display.set_mode((width * CELL_SIZE, height * CELL_SIZE))

    maze = hunt_and_kill.gen_maze(width, height)

    running = True
    while running:
        screen.fill(BG)

        draw_maze(screen, maze, width, height, FG)

        pygame.display.flip()

        clock.tick(60)

        for event in pygame.event.get():
            if event.type == pygame.QUIT:
                running = False

    pygame.quit()

    if input("Save? [Y/n]: ").strip().lower() != 'n':
        pygame.image.save(screen, "maze.jpg")


if __name__ == "__main__":
    # Send in cli args to size
    if len(argv) > 1:
        main(*map(int, argv[1].split('x')))
    else:
        main()
